##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Makefile
##

SRC	=	generator.c	\

compile:
	@gcc -o generator -g3 $(SRC)

clean:
	@rm -f *~
	@rm -f *.o

fclean:	clean
	@rm -f generator

re:	fclean compile
